### ISSUE TITLE
Resource endpoint discovery is broken

### ISSUE THREAD

**Issue by eed3si9n** [lightbend/reactive-lib#76]
originally discovered by @kikiya 

## steps

Lagom on GKE with Cassandra hosted elsewhere.

```
play.modules.enabled += "com.lightbend.rp.servicediscovery.lagom.javadsl.ServiceLocatorModule"
```

## problem

```
018-08-30 11:44:06.000 PDT
java.util.concurrent.CompletionException: java.net.URISyntaxException: Illegal character in scheme name at index 0: 128://10.128.0.6:0 at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292) at 
java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308) at
 java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:593) at 
 java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) at 
 java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617) at 
 java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1988) at 
 scala.concurrent.java8.FuturesConvertersImpl$CF.thenApply(FutureConvertersImpl.scala:27) at 
 scala.concurrent.java8.FuturesConvertersImpl$CF.thenApply(FutureConvertersImpl.scala:18) at 
 com.lightbend.rp.servicediscovery.javadsl.ServiceLocator.lookupOne(ServiceLocator.java:95) at 
 com.lightbend.rp.servicediscovery.lagom.javadsl.LagomServiceLocator.lambda$locate$0(LagomServiceLocator.java:44) at 
 java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) at 
 java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) at 
 java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) at 
 java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:561) at 
 java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:580) at 
 java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) at 
 java.lang.Thread.run(Thread.java:748) Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 0: 128://10.128.0.6:0 at java.net.URI$Parser.fail(URI.java:2848) at java.net.URI$Parser.checkChars(URI.java:3021) at 
 java.net.URI$Parser.checkChar(URI.java:3031) at java.net.URI$Parser.parse(URI.java:3047) at 
 java.net.URI.<init>(URI.java:673) at 
 com.lightbend.rp.servicediscovery.scaladsl.ServiceLocatorLike.$anonfun$translateResolved$1(ServiceLocator.scala:166) at 
 scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234) at 
 scala.collection.Iterator.foreach(Iterator.scala:929) at 
 scala.collection.Iterator.foreach$(Iterator.scala:929) at 
 scala.collection.AbstractIterator.foreach(Iterator.scala:1417) at 
 scala.collection.IterableLike.foreach(IterableLike.scala:71) at 
 scala.collection.IterableLike.foreach$(IterableLike.scala:70) at 
 scala.collection.AbstractIterable.foreach(Iterable.scala:54) at 
 scala.collection.TraversableLike.map(TraversableLike.scala:234) at 
 scala.collection.TraversableLike.map$(TraversableLike.scala:227) at 
 scala.collection.AbstractTraversable.map(Traversable.scala:104) at 
 com.lightbend.rp.servicediscovery.scaladsl.ServiceLocatorLike.translateResolved(ServiceLocator.scala:166) at 
 com.lightbend.rp.servicediscovery.scaladsl.ServiceLocatorLike.translateResolved$(ServiceLocator.scala:162) at 
 com.lightbend.rp.servicediscovery.scaladsl.ServiceLocator$.translateResolved(ServiceLocator.scala:64) at 
 com.lightbend.rp.servicediscovery.scaladsl.ServiceLocatorLike.$anonfun$doLookup$3(ServiceLocator.scala:287) at  

```

## expectation

resource endpoint is discovered.

## notes

Analysis provided by @kikiya 

```scala
def translateResolved(protocol: Option[String], hostname: String, addressARecord: Dns.Resolved): Seq[Service] =
    targetRuntime match {
      case Some(Kubernetes | Mesos) =>
        val uris =
          addressARecord.ipv4.map(v4 => new URI(protocol.orNull, null, v4.getHostAddress, 0, null, null, null)) ++
            addressARecord.ipv6.map(v6 => new URI(protocol.orNull, null, v6.getHostAddress, 0, null, null, null))

        uris.map(u => Service(hostname, u))

      case None =>
        Seq.empty
    }
```

> the port is being set to `0` by default and this is causing

```
textPayload:  "2018-09-04T16:06:29.793Z [[33mwarn[0m] com.lightbend.lagom.internal.persistence.cassandra.CassandraReadSideSessionProvider$ [sourceThread=application-lagom.persistence.dispatcher-50, akkaTimestamp=16:06:29.792UTC, akkaSource=CassandraReadSideSessionProvider$, sourceActorSystem=application] - Failed to connect to Cassandra and initialize. It will be retried on demand. Caused by: All host(s) tried for query failed (tried: /10.128.0.6:0 (com.datastax.driver.core.exceptions.TransportException: [/10.128.0.6:0] Cannot connect))
```

**Comment by TimMoore** [comment]
In the code above, it seems like it should call the four-argument version of the URI constructor, which doesn't take a port: https://docs.oracle.com/javase/8/docs/api/java/net/URI.html#URI-java.lang.String-java.lang.String-java.lang.String-java.lang.String-

> ```
> public URI(String scheme,
>            String host,
>            String path,
>            String fragment)
>     throws URISyntaxException
> ```
> Constructs a hierarchical URI from the given components.
> A component may be left undefined by passing `null`.
> 
> This convenience constructor works as if by invoking the seven-argument constructor as follows:
> ```
> new URI(scheme, null, host, -1, path, null, fragment);
> ```
