### ISSUE TITLE
Error in deploy

### ISSUE THREAD

**Issue by djKooks** [lightbend/reactive-lib#84]
Hello.
While following example in <https://developer.lightbend.com/docs/lightbend-orchestration/current/getting-started/sbt-play-minikube.html>, I faced error in:
```
[play-scala-seed] $ compile
[success] Total time: 5 s, completed Oct 6, 2018 9:01:50 PM
[play-scala-seed] $ deploy minikube
[info] Wrote /Users/kwangin/workspace/study/scala/play-scala-seed/target/scala-2.12/play-scala-seed_2.12-1.0-SNAPSHOT.pom
[info] role.rbac.authorization.k8s.io "pod-reader" deleted
[info] rolebinding.rbac.authorization.k8s.io "read-pods" deleted
[info] role.rbac.authorization.k8s.io/pod-reader created
[info] rolebinding.rbac.authorization.k8s.io/read-pods created
[info] Sending build context to Docker daemon  40.66MB
...
[info] Step 7/11 : ADD --chown=daemon:daemon opt /opt
[error] unable to convert uid/gid chown string to host mapping: can't find uid for user daemon: open /var/lib/docker/overlay2/e3a5133353c561365256b7e8b8a781a39e8523d2269674a9c6a8f4a80cd66ddd/merged/etc/passwd: no such file or directory
[error] java.lang.RuntimeException: Nonzero exit value: 1
[error] 	at com.typesafe.sbt.packager.docker.DockerPlugin$.publishLocalDocker(DockerPlugin.scala:335)
[error] 	at com.lightbend.rp.sbtreactiveapp.DeployableApp.$anonfun$projectSettings$12(Deploy.scala:191)
[error] 	at com.lightbend.rp.sbtreactiveapp.DeployableApp.$anonfun$projectSettings$12$adapted(Deploy.scala:52)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (deploy) Nonzero exit value: 1
```
I'm not sure It's okay to ask here. If I'm wrong, please let me know.

Thanks.

**Comment by TimMoore** [comment]
Hi @djKooks the best place to ask questions is https://discuss.lightbend.com/

Thanks!

**Comment by eed3si9n** [comment]
`ADD --chown=daemon:daemon opt /opt` is something that came from sbt-native-packager, not reactive-lib.
In the latest sbt-native-packager it should not emit that since I implemented the multi-stage Docker build.
